language: node_js
node_js:
  - "4.5.0"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
  NODE_ENV=travis
before_script:
  - sleep 10
services:
  - mongodb
script:
  - npm start &
  - sleep 10
  - npm test  